Gem::Specification.new do |s|
  is_jruby = RUBY_PLATFORM == "java"

  s.name        = "google-protobuf"
  s.version     = "4.31.0"
  git_tag       = "v#{s.version.to_s.sub('.rc.', '-rc')}" # Converts X.Y.Z.rc.N to vX.Y.Z-rcN, used for the git tag
  s.licenses    = ["BSD-3-Clause"]
  s.summary     = "Protocol Buffers"
  s.description = "Protocol Buffers are Google's data interchange format."
  s.homepage    = "https://developers.google.com/protocol-buffers"
  s.authors     = ["Protobuf Authors"]
  s.email       = "protobuf@googlegroups.com"
  s.metadata    = { "source_code_uri" => "https://github.com/protocolbuffers/protobuf/tree/#{git_tag}/ruby" }
  s.require_paths = ["lib"]

  if is_jruby
    s.platform  = "java"

    s.add_dependency "ffi", "~>1"
    s.add_dependency "ffi-compiler", "~>1"
  end

  files_globs = [
    is_jruby ? 'lib/**/*.{jar,rb,rake}' : 'lib/**/*.{rb,rake}',
    'ext/**/*',
  ]

  reject_ext_files_regex = if is_jruby
                             /^((convert|defs|map|repeated_field)\.[ch]|
                                   BUILD\.bazel|extconf\.rb|wrap_memcpy\.c)$/x
                           else
                             /^(BUILD\.bazel)$/
                           end

  s.files = Dir.glob(files_globs).reject do |file|
    File.directory?(file) || File.basename(file) =~ reject_ext_files_regex
  end

  s.extensions = is_jruby ? ["ext/google/protobuf_c/Rakefile"] : [
    # "Rakefile" will be replaced with "ext/google/protobuf_c/extconf.rb" in the
    # `rake gem` task.  When installing this gem via git or a local directory,
    # there are prerequisite rake tasks which ensure some autogenerated files
    # we need to build the C extension.  In the packaged Ruby gem, the necessary
    # autogenerated files will already be present.  See the initialization of
    # `Gem::PackageTask` in the Rakefile.
    "Rakefile",
    "ext/google/protobuf_c/Rakefile"
  ]

  s.required_ruby_version = '>= 3.1'
  # bigdecimal must be used as a non-built in gem as of ruby-3.4
  s.add_dependency "bigdecimal"
  # TODO: evaluate removing Rakefile and moving logic to extconf.rb, so that we
  # can remove this runtime dependency on rake. See the discussion here for
  # more details:
  # https://github.com/protocolbuffers/protobuf/pull/15203
  s.add_dependency "rake", ">= 13"
  s.add_development_dependency "ffi", "~>1"
  s.add_development_dependency "ffi-compiler", "~>1"
  s.add_development_dependency "rake-compiler", "~> 1.1.0"
  s.add_development_dependency "rake-compiler-dock", "= 1.2.1"
  s.add_development_dependency "test-unit", '~> 3.0', '>= 3.0.9'
end
